(function(root){
  'use strict';
  const F=CraveFresh,E=MealEngine,O=Ops,$=id=>document.getElementById(id),esc=O.escape;
  const storages={fridge:'Refrigerator ≤40°F',pantry:'Pantry / room storage',freezer:'Freezer ≤0°F','freeze-portions':'Keep first portion fresh; freeze the rest'};
  let getState,changed,asOf=F.today();
  const dateInput=(name,value,key)=>`<input type="date" value="${esc(value||'')}" min="2000-01-01" max="2100-12-31" data-fresh-field="${name}" data-fresh-key="${esc(key)}">`;
  const flag=b=>/Past|conflict/.test(b.status)?'danger':/soon/.test(b.status)?'soon':/checking/.test(b.status)?'unknown':'normal';
  function render(state){
    const f=state.freshness,data=F.analyze(state,state.plan,asOf),rows=data.batches;
    $('week-start').value=f.start;$('fresh-mode').value=f.mode;$('fresh-asof').value=asOf;
    const unknown=rows.filter(b=>/checking/.test(b.status));
    const attention=rows.filter(b=>/Past|conflict|soon/.test(b.status)).sort((a,b)=>(a.useBy||'9999').localeCompare(b.useBy||'9999'));
    $('fresh-attention').innerHTML=attention.length?attention.map(b=>`<a class="fresh-alert ${flag(b)}" href="#fresh-${esc(b.id)}"><strong>${esc(b.name)}</strong><span>${esc(b.status)} · ${b.useBy||'date unknown'} · ${b.kind==='planned'?'planned purchase':'already on hand'}</span></a>`).join(''):'<p>No immediate date alerts among batches with known dates.</p>';
    if(unknown.length)$('fresh-attention').innerHTML+=`<details class="fresh-alert unknown"><summary>${unknown.length} batches need label / storage dates</summary>${unknown.map(b=>`<p><a href="#fresh-${esc(b.id)}">${esc(b.name)}</a> · date unknown</p>`).join('')}</details>`;
    const trips=new Map();rows.filter(b=>b.kind==='planned').forEach(b=>{const k=b.boughtOn||'Unscheduled';const list=trips.get(k)||[];list.push(b);trips.set(k,list);});
    $('fresh-trips').innerHTML=[...trips].sort(([a],[b])=>a.localeCompare(b)).map(([date,list])=>`<div class="trip-card"><h4>${esc(date)}</h4><strong>~${O.money(E.sum(list,'cost'))}</strong><p>${list.map(b=>`${b.packs} × ${esc(b.name)}`).join('<br>')}</p></div>`).join('')||'<p>No additional purchases scheduled.</p>';
    const start=F.add(f.start,-1),days=Array.from({length:state.settings.days+5},(_,i)=>F.add(start,i));
    $('fresh-timeline').innerHTML=`<table class="fresh-chart"><caption>Purchase → storage window → estimated use-by / quality review. A dot marks preparation. Dates beyond this window are printed in the first column.</caption><thead><tr><th>Purchase batch / deadline</th>${days.map(d=>`<th>${d.slice(5)}</th>`).join('')}</tr></thead><tbody>${rows.map(b=>`<tr><th><a href="#fresh-${esc(b.id)}">${esc(b.name)}</a><small>${b.kind==='planned'?'To buy':'On hand'} · ${b.useBy||'Date unknown'}</small></th>${days.map(d=>{const buy=d===b.boughtOn,due=d===b.useBy,use=b.useDates.includes(d),active=b.boughtOn&&d>=b.boughtOn&&(!b.useBy||d<=b.useBy);return `<td class="${active?'life-window ':''}${due?'deadline ':''}${!b.useBy?'unknown-window ':''}" title="${esc(b.name+' · '+d+(buy?' · buy':'')+(due?' · use-by / review':'')+(use?' · prepare':''))}">${buy?'B':''}${use?' ●':''}${due?' ◆':''}</td>`;}).join('')}</tr>`).join('')}</tbody></table>`;
    $('fresh-batches').innerHTML=rows.map(b=>`<details class="fresh-batch ${flag(b)}" id="fresh-${esc(b.id)}"><summary><strong>${esc(b.name)}</strong> · ${b.packs} package${b.packs===1?'':'s'} · ${b.kind==='planned'?'buy '+(b.boughtOn||'date needed'):b.kind==='pantry'?'pantry supply':'bought '+(b.boughtOn||'date unknown')}<span>${esc(b.status)} · ${b.useBy?'use-by / review '+b.useBy:'enter a use-by date'}</span></summary><div class="form-grid three"><label>${b.kind==='planned'?'Buy on':'Purchased on'}${dateInput('boughtOn',b.boughtOn,b.id)}</label><label>Opened / cut on${dateInput('openedOn',b.openedOn,b.id)}</label><label>Package label date${dateInput('labelDate',b.labelDate,b.id)}</label><label>Storage<select data-fresh-field="storage" data-fresh-key="${esc(b.id)}">${Object.entries(storages).map(([k,v])=>`<option value="${k}" ${k===b.storage?'selected':''}>${esc(v)}</option>`).join('')}</select></label><label>Frozen on${dateInput('frozenOn',b.frozenOn,b.id)}</label><label>Fully thawed in refrigerator on${dateInput('thawedOn',b.thawedOn,b.id)}</label></div><p><strong>Prepare:</strong> ${b.useDates.join(', ')||'Unscheduled'}<br><strong>Eat:</strong> ${b.eatDates.join(', ')||'Unscheduled'}${b.thawDates.length?'<br><strong>Start thawing small portions:</strong> '+b.thawDates.join(', ')+' · allow more time for larger portions':''}</p><p>Estimated remaining in this batch: ${Number(b.remainingNow.toFixed(2))} ${b.unit} (after meals marked eaten and recorded waste). Allocated across the plan: ${Number(b.assigned.toFixed(2))} ${b.unit} · Unallocated surplus: ${Number(b.unallocated.toFixed(2))} ${b.unit}. ${esc(b.action)}</p><p class="fine-print">${esc(b.basis)}. ${esc(b.note)} <a href="${b.source}" target="_blank" rel="noopener noreferrer">Storage source ↗</a></p>${b.kind==='planned'?`<button class="button primary small" data-record-batch="${esc(b.id)}">Record purchase &amp; storage shown</button>`:''}</details>`).join('')||'<p>Choose meals or record bought packages to create purchase batches.</p>';
    $('fresh-cooking').innerHTML=data.meals.filter(m=>!m.meal.buy).map(m=>`<tr><td>${esc(E.recipeMap[m.meal.recipe].name)}<small>${esc(m.meal.slot)} · ${m.meal.eaten?'eaten':'planned'}</small></td><td>${m.eat}</td><td><input type="date" min="2000-01-01" max="${m.eat}" value="${m.cook}" data-prep-key="${m.id}" aria-label="Prepare ${esc(E.recipeMap[m.meal.recipe].name)} for ${m.eat}"></td><td>${m.useBy}<small>${esc(m.basis)}</small></td><td>${esc(m.status)}</td></tr>`).join('');
  }
  function install(options){getState=options.getState;changed=options.changed;
    $('freshness').addEventListener('change',ev=>{
      const el=ev.target,s=getState();try{
        if(el.id==='fresh-asof'){if(!F.validDate(el.value))throw Error('Choose a valid review date.');asOf=el.value;render(s);return;}
        if(el.id==='week-start'){if(!F.validDate(el.value))throw Error('Choose a valid week start.');s.freshness.start=el.value;}
        if(el.id==='fresh-mode')s.freshness.mode=el.value;
        if(el.dataset.prepKey){if(!el.checkValidity()||!F.validDate(el.value))throw Error('Preparation must be on or before the meal date.');s.freshness.prep[el.dataset.prepKey]=el.value;}
        if(el.dataset.freshKey){if(el.type==='date'&&el.value&&!F.validDate(el.value))throw Error('Choose a valid date.');const lot=s.freshness.lots.find(l=>l.id===el.dataset.freshKey),target=lot||(s.freshness.overrides[el.dataset.freshKey]||={});target[el.dataset.freshField]=el.value;}
        changed();$('fresh-status').textContent='Dates updated. Shopping, freshness alerts and CSV exports use these entries.';
      }catch(err){$('fresh-status').textContent=err.message;render(s);}
    });
    $('freshness').addEventListener('click',ev=>{const link=ev.target.closest('a[href^="#fresh-"]');if(link){const target=document.getElementById(link.getAttribute('href').slice(1));if(target)target.open=true;}const button=ev.target.closest('[data-record-batch]');if(!button)return;const s=getState(),row=F.analyze(s,s.plan,asOf).batches.find(b=>b.id===button.dataset.recordBatch);if(!row)return;
      if(!row.boughtOn||row.boughtOn>F.today()){$('fresh-status').textContent='Set the actual purchase date (today or earlier) before recording this purchase.';return;}
      s.freshness.lots.push({id:'lot-'+Date.now()+'-'+Math.random().toString(36).slice(2,8),ingredient:row.ingredient,packs:row.packs,boughtOn:row.boughtOn,openedOn:row.openedOn||'',labelDate:row.labelDate||'',storage:row.storage,frozenOn:row.frozenOn||'',thawedOn:row.thawedOn||''});s.purchased[row.ingredient]=(s.purchased[row.ingredient]||0)+row.packs;delete s.freshness.overrides[row.id];changed();$('fresh-status').textContent='Purchase recorded as a dated batch. Later purchases keep their own dates.';
    });
    $('print-freshness').addEventListener('click',()=>root.print());
  }
  function shoppingRows(state){return F.analyze(state).batches.map(b=>({purchase_batch:b.id,purchase_status:b.kind,ingredient:b.name,aisle:MealData.ingredients[b.ingredient].aisle,quantity_needed:Number(b.assigned.toFixed(2)),unit:b.unit,package_size:b.pack,packages_to_buy:b.kind==='planned'?b.packs:0,packages_already_bought:b.kind==='bought'?b.packs:0,buy_on:b.kind==='planned'?b.boughtOn:'',purchased_on:b.kind==='bought'?b.boughtOn:'',opened_or_cut_on:b.openedOn||'',storage:b.storage,freeze_on:b.freezeOn,thawed_on:b.thawedOn||'',start_thawing_on:b.thawDates.join('; '),cook_or_prepare_on:b.useDates.join('; '),eat_on:b.eatDates.join('; '),label_date:b.labelDate||'',estimated_use_by_or_review:b.useBy,deadline_basis:b.basis,freshness_status:b.status,estimated_remaining_quantity:Number(b.remainingNow.toFixed(2)),surplus_quantity:Number(b.unallocated.toFixed(2)),discarded_quantity:b.wasted||0,reference_package_price_usd:b.price,reference_checkout_usd:b.cost,action:b.action,storage_source:b.source,...Object.fromEntries(['walmart','kroger','target'].flatMap(store=>{const q=encodeURIComponent(b.name),url=store==='walmart'?`https://www.walmart.com/search?q=${q}`:store==='kroger'?`https://www.kroger.com/search?query=${q}`:`https://www.target.com/s?searchTerm=${q}`,l=CraveCommerce.resolve(store,url,b.name);return [[store+'_package_quote_usd',state.quotes[store][b.ingredient]??''],[store+'_search',l.url],[store+'_disclosure',l.paid?'We may earn a commission if you buy through this link.':'']];}))}));}
  root.CraveFreshView={render,install,shoppingRows};
})(globalThis);
