/* Evaluate after data.js and engine.js in a browser; runMealTests() returns results. */
function runMealTests(){
  const D=MealData,E=MealEngine,results=[];
  const test=(name,fn)=>{try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}};
  const assert=(v,m='Assertion failed')=>{if(!v)throw Error(m);};
  const near=(a,b)=>assert(Math.abs(a-b)<1e-7,`${a} != ${b}`);
  const throws=fn=>{let threw=false;try{fn();}catch{threw=true;}assert(threw,'Expected rejection');};
  const settings={calories:2200,people:1,days:3,budget:85,cookTime:60,protein:90,diet:'balanced',dairyFree:false,reuse:true,quick:true};
  const meal={recipe:'chicken-rice',portion:1,slot:'dinner',locked:false};
  test('All recipe IDs are unique',()=>assert(new Set(D.recipes.map(r=>r.id)).size===D.recipes.length));
  test('Every menu favorite has a unique working recipe',()=>{assert(new Set(D.menu.map(m=>m.recipe)).size===D.menu.length);D.menu.forEach(m=>assert(E.recipeMap[m.recipe]&&m.restaurant&&m.item));});
  test('Every ingredient reference and quantity is valid',()=>D.recipes.forEach(r=>r.parts.forEach(p=>assert(D.ingredients[p.id]&&p.qty>0&&Number.isFinite(p.qty)))));
  test('All recipes include instructions and nonnegative times',()=>D.recipes.forEach(r=>assert(r.steps.length&&r.prep>=0&&r.cook>=0)));
  test('All recipe nutrition is positive and finite',()=>D.recipes.forEach(r=>{const n=E.nutrition(r);assert(n.kcal>0&&n.protein>=0&&n.cost>0&&Object.values(n).every(Number.isFinite));}));
  test('Portions scale nutrition and cost linearly',()=>{const n=E.nutrition(D.recipes[0]),double=E.nutrition(D.recipes[0],2);Object.keys(n).forEach(k=>near(double[k],n[k]*2));});
  test('Edited ingredient price affects recipe cost',()=>{const r=E.recipeMap['chicken-rice'];assert(E.nutrition(r,1,{chicken:30}).cost>E.nutrition(r).cost);});
  test('Gross MET formula matches 82kg example',()=>near(E.activity(3.3,82,1,530).rate,4.7355));
  test('Walking equivalent equals meal kcal / burn rate',()=>near(E.activity(3.3,82,30,530).equivalent,530/4.7355));
  test('Meal percentage uses selected duration and energy',()=>near(E.activity(6.8,82,30,530).percent,(6.8*3.5*82/200*30)/530*100));
  test('Net activity subtracts resting MET',()=>near(E.activity(6.8,82,30,530,'net').energy,(6.8-1)*3.5*82/200*30));
  test('A percentage over 100 is not truncated in the math',()=>assert(E.activity(9.3,82,90,100).percent>100));
  test('Net rest has zero energy and no finite equivalent',()=>{const n=E.activity(1,82,30,530,'net');near(n.energy,0);assert(n.equivalent===null);});
  test('Invalid MET, weight and meal energy rejected',()=>{throws(()=>E.activity(0,82,30,530));throws(()=>E.activity(3.8,-1,30,530));throws(()=>E.activity(3.8,82,30,0));throws(()=>E.activity(3.8,82,NaN,530));});
  test('Invalid settings rejected',()=>{throws(()=>E.validateSettings({...settings,calories:0}));throws(()=>E.validateSettings({...settings,days:2.2}));throws(()=>E.validateSettings({...settings,budget:Infinity}));});
  test('Settings strip unrecognized fields',()=>assert(!Object.hasOwn(E.validateSettings({...settings,unknown:42}),'unknown')));
  test('Vegan recipes contain no meat, dairy, eggs, fish or honey',()=>D.recipes.filter(r=>E.allowed(r,{...settings,diet:'vegan'})).forEach(r=>r.parts.forEach(p=>assert(!['chicken','beef','egg','yogurt','cheese','feta','tuna','salmon','honey','mayo'].includes(p.id)))));
  test('Dairy-free filter blocks all marked milk ingredients',()=>D.recipes.filter(r=>E.allowed(r,{...settings,dairyFree:true})).forEach(r=>r.parts.forEach(p=>assert(!D.ingredients[p.id].allergens.includes('milk')))));
  const plans={};
  for(const diet of ['balanced','high-protein','low-carb','mediterranean','vegetarian','vegan','keto'])test(diet+' builder produces complete matching days',()=>{const s={...settings,diet};const plan=E.build(s);plans[diet]=plan;assert(plan.length===s.days);plan.forEach(day=>{assert(day.length===4);assert(new Set(day.map(m=>m.slot)).size===4);day.forEach(m=>assert(E.allowed(E.recipeMap[m.recipe],s)));});});
  test('Builder is deterministic',()=>assert(JSON.stringify(E.build(settings))===JSON.stringify(plans.balanced)));
  test('Pinned cravings survive rebuilding',()=>{const pinned={recipe:'crunchwrap',portion:1,slot:'dinner',locked:true};const plan=E.build(settings,[[pinned]]);assert(plan[0].some(m=>JSON.stringify(m)===JSON.stringify(pinned)));});
  test('Incompatible pinned meals rejected',()=>throws(()=>E.build({...settings,diet:'vegan'},[[{...meal,locked:true}]])));
  test('Dairy-free high-protein meals remain within both filters',()=>{const s={...settings,diet:'high-protein',dairyFree:true};E.build(s).flat().forEach(m=>assert(E.allowed(E.recipeMap[m.recipe],s)));});
  test('Activity-adjusted targets influence meal building',()=>{const high=E.build(settings,[],{},[2700,2700,2700]);assert(E.sum(high.map(d=>E.dayTotals(d)),'kcal')>E.sum(plans.balanced.map(d=>E.dayTotals(d)),'kcal'));});
  test('Household shopping quantities scale independently of nutrition',()=>{const a=E.shopping([[meal]],1),b=E.shopping([[meal]],2);a.forEach(i=>near(b.find(j=>j.id===i.id).qty,i.qty*2));near(E.dayTotals([meal]).kcal,E.nutrition(E.recipeMap[meal.recipe]).kcal);});
  test('Shopping consolidates repeated ingredients',()=>{const cart=E.shopping([[meal],[meal]],1);assert(cart.length===E.recipeMap[meal.recipe].parts.length);near(cart.find(i=>i.id==='chicken').qty,340);});
  test('Shopping rounds packages up and computes leftover',()=>{const i=E.shopping([[meal]],1).find(i=>i.id==='chicken');assert(i.packs===1);near(i.leftover,730);});
  test('Exact package boundary does not buy an extra pack',()=>{const m={recipe:'banana-snack',portion:1,slot:'snack'};const i=E.shopping([[m,m,m,m,m]],1).find(i=>i.id==='banana');assert(i.packs===1);near(i.leftover,0);});
  test('Pantry removes package purchases, not meal ingredients',()=>{const i=E.shopping([[meal]],1,{chicken:true}).find(i=>i.id==='chicken');near(i.packs,0);near(i.total,0);near(i.qty,170);});
  test('Zero-dollar package price is valid',()=>near(E.shopping([[meal]],1,{}, {chicken:0}).find(i=>i.id==='chicken').total,0));
  test('Activity credit defaults to zero and uses net with 50%',()=>{const w=[{day:0,met:6.8,kg:82,minutes:30}];near(E.credits(w,0,0),0);near(E.credits(w,0,.5),(6.8-1)*3.5*82/200*30*.5);near(E.credits(w,1,1),0);});
  test('Impossible budget is surfaced',()=>assert(E.warnings(plans.balanced,{...settings,budget:10}).some(w=>w.includes('grocery checkout'))));
  const session={version:1,settings,plan:plans.balanced,pantry:{},prices:{},quotes:{walmart:{},kroger:{},target:{}},checked:{},workouts:[],strategy:0};
  test('Session round-trip preserves plans',()=>{const restored=E.validateSession(JSON.parse(JSON.stringify(session)));session.plan.forEach((day,i)=>day.forEach((m,j)=>Object.keys(m).forEach(k=>assert(m[k]===restored.plan[i][j][k]))));});
  test('Invalid imported recipes are rejected',()=>{const s=structuredClone(session);s.plan[0][0].recipe='not-a-recipe';throws(()=>E.validateSession(s));});
  test('Non-finite imported store quotes are rejected',()=>{const s=structuredClone(session);s.quotes.walmart.chicken=Infinity;throws(()=>E.validateSession(s));});
  test('Imported workout MET uses source value, not supplied value',()=>{const s=structuredClone(session);s.workouts=[{day:0,activity:'walk',met:99,kg:82,minutes:30}];near(E.validateSession(s).workouts[0].met,3.8);});
  test('Workout outside the plan rejected',()=>{const s=structuredClone(session);s.workouts=[{day:8,activity:'walk',kg:82,minutes:30}];throws(()=>E.validateSession(s));});
  const bought={recipe:'big-mac',portion:2,slot:'dinner',locked:true,buy:{kcal:580,cost:8.25}};
  test('Restaurant portions scale calories and cost with zero cooking',()=>{const n=E.dayTotals([bought]);near(n.kcal,1160);near(n.cost,16.5);near(n.time,0);assert(E.shopping([[bought]],2).length===0);});
  test('Restaurant snapshots survive rebuilding',()=>{const plan=E.build(settings,[[bought]]);assert(JSON.stringify(plan[0].find(m=>m.buy))===JSON.stringify(bought));});
  test('Restaurant purchase plus groceries is compared with food budget',()=>assert(E.warnings([[{...bought,buy:{kcal:580,cost:100}}]],{...settings,days:1,budget:50}).some(w=>w.includes('$150.00 above'))));
  test('Restaurant unknown macros suppress incomplete macro goal judgments',()=>{const notes=E.warnings([[bought]],{...settings,protein:200,diet:'keto'});assert(notes.some(w=>w.includes('cannot be assessed')));assert(!notes.some(w=>w.includes('g protein, below')));});
  test('Extra grocery quantities add to shopping without changing day calories',()=>{const extras=[{recipe:meal.recipe,portion:2}],cart=E.shopping([[meal,bought]],2,{}, {},extras);near(cart.find(i=>i.id==='chicken').qty,1020);near(E.dayTotals([meal,bought]).kcal,E.nutrition(E.recipeMap[meal.recipe]).kcal+1160);});
  test('Buy meals and extra groceries survive JSON save validation',()=>{const raw=structuredClone(session);raw.plan[0]=[bought];raw.shoppingExtras=[{recipe:'big-mac',portion:1}];const out=E.validateSession(raw);near(out.plan[0][0].buy.cost,8.25);assert(out.shoppingExtras[0].recipe==='big-mac');});
  test('Missing, invalid and nonfinite restaurant quotes are rejected',()=>{for(const buy of [{kcal:580,cost:null},{kcal:0,cost:5},{kcal:580,cost:Infinity}]){const raw=structuredClone(session);raw.plan[0]=[{...bought,buy}];throws(()=>E.validateSession(raw));}});
  test('Invalid extra groceries are rejected',()=>{const raw=structuredClone(session);raw.shoppingExtras=[{recipe:'unknown',portion:1}];throws(()=>E.validateSession(raw));});
  return results;
}
