/* Load after data.js and engine.js; runMealTests() verifies chosen-day planning. */
function runMealTests(){
  const D=MealData,E=MealEngine,results=[];
  const test=(name,fn)=>{try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}};
  const assert=(v,m='Assertion failed')=>{if(!v)throw Error(m);};
  const near=(a,b)=>assert(Math.abs(a-b)<1e-7,`${a} != ${b}`);
  const throws=fn=>{let threw=false;try{fn();}catch{threw=true;}assert(threw,'Expected rejection');};
  const settings={calories:2200,people:1,days:7,budget:85,cookTime:60,protein:90,diet:'balanced',dairyFree:false,reuse:false,quick:false};
  const meal={recipe:'overnight-oats',portion:1,slot:'breakfast'},empty=E.resizePlan(settings),week=E.schedule(empty,meal,0,5);
  const session={version:1,settings,plan:week,pantry:{},prices:{},quotes:{walmart:{},kroger:{},target:{}},checked:{},workouts:[],strategy:0,shoppingExtras:[],purchased:{}};
  test('New weeks contain no generated meals',()=>assert(empty.length===7&&empty.every(d=>d.length===0)&&!E.build));
  test('All menu entries have unique working recipes',()=>{assert(new Set(D.menu.map(m=>m.recipe)).size===D.menu.length);D.menu.forEach(m=>assert(E.recipeMap[m.recipe]));});
  test('Every ingredient reference, quantity and recipe nutrition is valid',()=>D.recipes.forEach(r=>{r.parts.forEach(p=>assert(D.ingredients[p.id]&&p.qty>0));assert(r.steps.length&&Object.values(E.nutrition(r)).every(Number.isFinite)&&E.nutrition(r).kcal>0);}));
  test('Five breakfasts fills only the selected days and slots',()=>{assert(week.slice(0,5).every(d=>d.length===1&&d[0].recipe===meal.recipe&&d[0].slot==='breakfast'));assert(week.slice(5).every(d=>!d.length));});
  test('Scheduling does not mutate the previous week',()=>assert(empty.every(d=>!d.length)));
  test('Repeating a selection replaces slots without duplicating groceries',()=>assert(JSON.stringify(E.schedule(week,meal,0,5))===JSON.stringify(week)));
  test('Lunch choices preserve chosen breakfasts',()=>{const p=E.schedule(week,{recipe:'chicken-rice',slot:'lunch',portion:1},1,3);assert(p[0].length===1&&p[1].length===2&&p[4].length===1);});
  test('Selections outside the week and invalid portions are rejected',()=>{throws(()=>E.schedule(week,meal,5,3));throws(()=>E.schedule(week,meal,0,0));throws(()=>E.schedule(week,{...meal,portion:.3},0,1));});
  test('Full-day failures are atomic across multiple selected days',()=>{const full=structuredClone(empty);full[1]=Array.from({length:12},()=>({...meal,slot:'extra'}));throws(()=>E.schedule(full,{...meal,slot:'extra'},0,2));assert(full[0].length===0);});
  test('Preference edits retain every user choice and eaten state',()=>{const p=structuredClone(week);p[0][0].eaten=true;const resized=E.resizePlan({...settings,diet:'keto',calories:2400},p);assert(JSON.stringify(resized)===JSON.stringify(p));});
  test('Shortening cannot silently discard chosen meals',()=>throws(()=>E.resizePlan({...settings,days:3},week)));
  test('Empty trailing days can be shortened',()=>assert(E.resizePlan({...settings,days:5},week).length===5));
  test('Partial days do not trigger below-target nags',()=>assert(!E.warnings(week,settings).some(w=>w.includes('below'))));
  test('Diet filtering remains available without choosing meals',()=>D.recipes.filter(r=>E.allowed(r,{...settings,diet:'vegan'})).forEach(r=>r.parts.forEach(p=>assert(!['chicken','beef','egg','yogurt','cheese','feta','tuna','salmon','honey','mayo'].includes(p.id)))));
  test('Five breakfasts share one oats package, not five',()=>{const i=E.shopping(week,1).find(i=>i.id==='oats');near(i.qty,325);near(i.packs,1);near(i.total,D.ingredients.oats.price);});
  test('All meals share ingredient packages before rounding',()=>{const p=E.schedule(week,{recipe:'yogurt-bowl',slot:'lunch',portion:1},0,2),i=E.shopping(p,1).find(i=>i.id==='oats');near(i.qty,415);near(i.packs,1);});
  test('Household servings scale ingredient quantities',()=>near(E.shopping(week,2).find(i=>i.id==='oats').qty,650));
  test('Bought packages cover later breakfasts',()=>{const p=E.schedule(week,meal,5,2),i=E.shopping(p,1,{}, {},[],{oats:1}).find(i=>i.id==='oats');near(i.qty,455);near(i.packs,0);near(i.total,0);});
  test('Crossing a bought package boundary charges only additional packages',()=>{const p=E.schedule(empty,{...meal,portion:4},0,7),i=E.shopping(p,1,{}, {},[],{oats:1}).find(i=>i.id==='oats');near(i.packs,Math.ceil(1820/D.ingredients.oats.pack)-1);});
  test('Eaten meals keep their grocery allocation',()=>{const p=structuredClone(week);p[0][0].eaten=true;assert(JSON.stringify(E.shopping(p,1))===JSON.stringify(E.shopping(week,1)));});
  test('Purchased inventory remains visible after removing a meal',()=>{const i=E.shopping(empty,1,{}, {},[],{oats:1}).find(i=>i.id==='oats');near(i.qty,0);near(i.bought,1);near(i.packs,0);near(i.leftover,D.ingredients.oats.pack);});
  test('Pantry supply covers all required purchases',()=>near(E.shopping(week,1,{oats:true}).find(i=>i.id==='oats').packs,0));
  test('Restaurant choices add calories but no grocery packages',()=>{const p=E.schedule(empty,{recipe:'big-mac',slot:'dinner',portion:1,buy:{kcal:580,cost:8}},0,2);near(E.dayTotals(p[0]).kcal,580);near(E.dayTotals(p[0]).cost,8);assert(E.shopping(p,1).length===0);});
  test('Saved week preserves purchases, progress and extra batch quantities',()=>{const raw=structuredClone(session);raw.plan[0][0].eaten=true;raw.purchased={oats:1};raw.shoppingExtras=[{recipe:meal.recipe,portion:7}];const out=E.validateSession(raw);assert(out.plan[0][0].eaten);near(out.purchased.oats,1);near(out.shoppingExtras[0].portion,7);});
  test('Older saved checkmarks migrate to package counts',()=>{const raw=structuredClone(session);delete raw.purchased;raw.checked.oats=true;near(E.validateSession(raw).purchased.oats,1);});
  test('Changed eating preferences do not invalidate saved chosen meals',()=>{const raw=structuredClone(session);raw.settings.diet='keto';assert(E.validateSession(raw).plan[0][0].recipe===meal.recipe);});
  test('Invalid saved purchases, recipes and extra quantities are rejected',()=>{for(const change of [r=>r.purchased.oats=-1,r=>r.plan[0][0].recipe='missing',r=>r.shoppingExtras=[{recipe:meal.recipe,portion:Infinity}]]){const raw=structuredClone(session);change(raw);throws(()=>E.validateSession(raw));}});
  test('MET energy and uncapped meal percentages are unchanged',()=>{near(E.activity(3.3,82,1,530).rate,4.7355);near(E.activity(6.8,82,30,530).percent,(6.8*3.5*82/200*30)/530*100);assert(E.activity(9.3,82,90,100).percent>100);});
  test('Optional activity credits use net energy',()=>near(E.credits([{day:0,met:6.8,kg:82,minutes:30}],0,.5),5.8*3.5*82/200*30*.5));
  test('Imported workouts use verified source MET and valid days',()=>{const raw=structuredClone(session);raw.workouts=[{day:0,activity:'walk',met:99,kg:82,minutes:30}];near(E.validateSession(raw).workouts[0].met,3.8);raw.workouts[0].day=7;throws(()=>E.validateSession(raw));});
  return results;
}
