/* global Ops */
(function () {
  'use strict';
  const O = Ops, $ = id => document.getElementById(id), e = O.escape, form = $('ticket-form');
  let rows = [], rules = structuredClone(O.defaultRules), cutoff = new Date().toISOString().slice(0,19)+'Z', reported = null, editing = -1, audit;
  const pct = n => n === null ? '—' : n.toFixed(1)+'%';
  const message = (id,text,error=false) => { $(id).textContent=text; $(id).classList.toggle('error',error); };
  const empty = (cols,text) => `<tr><td colspan="${cols}" class="empty">${text}</td></tr>`;
  $('rule-rows').innerHTML = Object.entries(rules).map(([p,r]) => `<tr><td><span class="badge">${p}</span></td><td><input class="rule-input" id="${p}-response" aria-label="${p} response target in minutes" type="number" min="0.001" max="1000000" step="any" value="${r.response}" required></td><td><input class="rule-input" id="${p}-resolution" aria-label="${p} resolution target in hours" type="number" min="0.001" max="1000000" step="any" value="${r.resolution}" required></td></tr>`).join('');
  $('cutoff').value=cutoff.slice(0,19);
  function resetForm() { form.reset(); editing=-1; $('entry-title').textContent='Add a service ticket'; $('save-ticket').textContent='Add ticket +'; $('cancel-edit').hidden=true; }
  $('rules-form').addEventListener('submit',ev => { ev.preventDefault(); try { const next = Object.fromEntries(Object.keys(rules).map(p => [p,{ response:O.number($(p+'-response').value,p+' response',{ min:0.001,max:1e6 }),resolution:O.number($(p+'-resolution').value,p+' resolution',{ min:0.001,max:1e6 }) }])); const date=$('cutoff').value+'Z'; const rep=$('reported').value===''?null:O.number($('reported').value,'Reported compliance',{ max:100 }); O.auditTickets(rows,next,date); rules=next; cutoff=date; reported=rep; render(); message('rules-status','Rules and report cutoff applied.'); } catch(err) { message('rules-status',err.message+' Previous rules remain applied.',true); } });
  form.addEventListener('submit',ev => { ev.preventDefault(); try { const raw=Object.fromEntries(new FormData(form)); for (const f of ['opened_at','responded_at','resolved_at']) if(raw[f]) raw[f]+='Z'; const r=O.validateTicket(raw), next=[...rows]; if(editing<0) { if(rows.length>=10000) throw new Error('The workspace supports at most 10,000 tickets.'); next.push(r); } else next[editing]=r; O.auditTickets(next,rules,cutoff); rows=next; resetForm(); render(); message('entry-status','Ticket saved. Scorecard updated for the applied cutoff.'); } catch(err) { message('entry-status',err.message,true); } });
  $('cancel-edit').addEventListener('click',()=>{resetForm(); message('entry-status','Edit canceled.');});
  $('tickets').addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;const i=+b.dataset.index;if(b.dataset.action==='remove'){rows.splice(i,1);resetForm();render();message('status','Ticket removed.');}else{editing=i;for(const h of O.ticketHeaders) form.elements[h].value = h.endsWith('_at') && rows[i][h] ? new Date(rows[i][h]).toISOString().slice(0,19) : rows[i][h];$('entry-title').textContent='Edit service ticket';$('save-ticket').textContent='Save changes';$('cancel-edit').hidden=false;$('entry').scrollIntoView({behavior:'smooth'});form.elements.ticket_id.focus({preventScroll:true});}});
  $('template').addEventListener('click',()=>O.download('slacheck-ticket-template.csv',O.ticketHeaders,[]));
  $('import').addEventListener('change',async ev=>{try{const imported=await O.readFile(ev.target.files[0],['ticket_id','vendor','priority','opened_at'],O.validateTicket);if(!imported)return;O.auditTickets(imported,rules,cutoff);rows=imported;resetForm();render();message('status',`Imported ${rows.length} tickets. Previous ticket list replaced.`);}catch(err){message('status',err.message+' Your current tickets are unchanged.',true);}finally{ev.target.value='';}});
  $('sample').addEventListener('click',()=>{const ago=hours=>new Date(Date.parse(cutoff)-hours*3600000).toISOString(); rows=[{ticket_id:'INC-1001',vendor:'Atlas Services',priority:'P1',opened_at:ago(48),responded_at:ago(47.9),resolved_at:ago(45),owner:'Facilities',issue_key:'rack-12-power'},{ticket_id:'INC-1002',vendor:'Atlas Services',priority:'P1',opened_at:ago(24),responded_at:ago(23.5),resolved_at:ago(18),owner:'Facilities',issue_key:'rack-12-power'},{ticket_id:'INC-1003',vendor:'Atlas Services',priority:'P2',opened_at:ago(12),responded_at:ago(11.5),resolved_at:'',owner:'Vendor manager',issue_key:'cooling-zone-b'},{ticket_id:'INC-1004',vendor:'Relay Support',priority:'P3',opened_at:ago(2),responded_at:'',resolved_at:'',owner:'IT operations',issue_key:'vpn-access'},{ticket_id:'INC-1005',vendor:'Relay Support',priority:'P2',opened_at:ago(20),responded_at:ago(19.5),resolved_at:ago(15),owner:'IT operations',issue_key:'switch-07'}].map(O.validateTicket);resetForm();render();message('status','Fictional example loaded relative to the applied report cutoff. Current SLA rules retained.');});
  $('clear').addEventListener('click',()=>{rows=[];resetForm();render();message('status','Tickets cleared. SLA rules retained.');});
  function actionRows(){return audit.tickets.filter(r=>r.response.status==='Breached'||r.resolution.status==='Breached').map(r=>({ticket_id:r.ticket_id,vendor:r.vendor,priority:r.priority,owner:r.owner||'Unassigned',response_status:r.response.status,resolution_status:r.resolution.status,action:!r.resolution.complete?'Request recovery plan and resolution ETA; document cause of breach.':'Review breach cause and agree a prevention action.',due_date:'',status:'Open',evidence:`Opened ${r.opened_at}; response ${r.responded_at||'missing'}; resolution ${r.resolved_at||'missing'}; cutoff ${cutoff}`,notes:''}));}
  function render(){
    audit=O.auditTickets(rows,rules,cutoff);const a=audit;
    $('scope').textContent=`As of ${new Date(cutoff).toISOString().replace('T',' ').replace('.000Z',' UTC')} · ${a.count} tickets · ${a.pending} pending checks excluded from compliance.`;
    $('print-rules').textContent='Applied targets: '+Object.entries(rules).map(([p,r])=>`${p}: response ≤ ${r.response} min / resolution ≤ ${r.resolution} hr`).join(' · ');
    const metrics=[['SLA compliance',pct(a.compliance),'Met checks / (met + breached checks)'],['Response breaches',a.responseBreaches,'Response took too long or is overdue'],['Resolution breaches',a.resolutionBreaches,'Resolution took too long or is overdue'],['Open tickets',a.open,'Unresolved as of the report cutoff']];
    $('metrics').innerHTML=metrics.map(([label,value,note],i)=>`<div class="metric ${i===0?'featured':''}"><div class="metric-label">${e(label)}</div><div class="metric-value">${e(value)}</div><div class="metric-note">${e(note)}</div></div>`).join('');
    $('comparison').textContent=reported===null?'Enter vendor-reported compliance above to compare the same check-level metric.':a.compliance===null?`Vendor reported ${pct(reported)}. No completed or overdue checks to compare.`:`Vendor reported ${pct(reported)} · calculated ${pct(a.compliance)} · difference ${(a.compliance-reported).toFixed(1)} percentage points. Compare only identical scope and definitions.`;
    $('scorecard').innerHTML=a.vendors.slice(0,100).map(v=>`<tr><td><strong>${e(v.vendor)}</strong></td><td class="num">${v.count}</td><td class="num">${v.responseBreaches}</td><td class="num">${v.resolutionBreaches}</td><td class="num">${v.pending}</td><td class="num"><span class="badge ${v.compliance!==null&&v.compliance<100?'warn':''}">${pct(v.compliance)}</span></td></tr>`).join('')||empty(6,'<strong>No tickets to audit yet.</strong>Load the example or add your service data to see a scorecard.');
    const milestone=m=>`<span class="badge ${m.status==='Breached'?'bad':m.status==='Pending'?'warn':''}">${m.status}</span><small>${m.minutes.toFixed(1)} min ${m.complete?'elapsed':'so far'}</small>`;
    $('ticket-count').textContent=`${rows.length} tickets · ${rows.length>200?'Showing first 200; CSV exports include all tickets':'Each milestone measured from opening'}`;
    $('tickets').innerHTML=a.tickets.slice(0,200).map((r,i)=>`<tr><td><strong>${e(r.ticket_id)}</strong><small>${e(r.vendor)}</small></td><td>${e(r.priority)}</td><td>${milestone(r.response)}</td><td>${milestone(r.resolution)}</td><td class="num">${r.resolution.complete?'—':r.ageHours.toFixed(1)+' hr'}</td><td>${e(r.owner||'Unassigned')}</td><td class="no-print"><div class="actions"><button class="small" data-action="edit" data-index="${i}" aria-label="Edit ticket ${e(r.ticket_id)}">Edit</button><button class="small danger" data-action="remove" data-index="${i}" aria-label="Remove ticket ${e(r.ticket_id)}">×</button></div></td></tr>`).join('')||empty(7,'Your ticket-level evidence will appear here.');
    const actions=actionRows();$('actions-list').innerHTML=actions.slice(0,50).map(r=>`<div class="panel-body" style="border-bottom:1px solid var(--line)"><h3>${e(r.ticket_id)} <span class="badge bad">${e(r.priority)} breach</span></h3><div class="helper">${e(r.vendor)} · Owner: ${e(r.owner)}</div><p class="helper">${e(r.action)}</p></div>`).join('')||'<div class="empty">'+(rows.length?'No breached tickets under the current rules.':'Breach follow-ups will appear here.')+'</div>';
    $('display-limits').hidden=rows.length<=200 && a.vendors.length<=100 && actions.length<=50 && a.repeats.length<=50;
    $('repeats').innerHTML=a.repeats.slice(0,50).map(g=>`<div class="panel-body" style="border-bottom:1px solid var(--line)"><h3>${e(g[0].issue_key)} <span class="badge warn">${g.length} tickets</span></h3><div class="helper">${e(g[0].vendor)} · ${e(g.map(r=>r.ticket_id).join(', '))}</div></div>`).join('')||'<div class="empty">No repeated issue keys in this dataset.</div>';
    for(const id of ['export-scorecard','export-tickets','export-audit','export-actions'])$(id).disabled=!rows.length;
  }
  function ruleRows(){return Object.entries(rules).map(([priority,r])=>({priority,response_minutes:r.response,resolution_hours:r.resolution,clock:'24/7 elapsed from opened_at',cutoff_utc:cutoff}));}
  $('export-rules').addEventListener('click',()=>O.download('slacheck-rules.csv',['priority','response_minutes','resolution_hours','clock','cutoff_utc'],ruleRows()));
  $('export-tickets').addEventListener('click',()=>O.download('slacheck-tickets.csv',O.ticketHeaders,rows));
  $('export-scorecard').addEventListener('click',()=>O.download('slacheck-scorecard.csv',['vendor','tickets','response_breaches','resolution_breaches','open_tickets','pending_checks','compliance_percent','cutoff_utc','clock','applied_rules'],audit.vendors.map(v=>({vendor:v.vendor,tickets:v.count,response_breaches:v.responseBreaches,resolution_breaches:v.resolutionBreaches,open_tickets:v.open,pending_checks:v.pending,compliance_percent:v.compliance===null?'':v.compliance.toFixed(2),cutoff_utc:cutoff,clock:'24/7 elapsed from opened_at',applied_rules:ruleRows().map(r=>`${r.priority}: ${r.response_minutes} min response / ${r.resolution_hours} hr resolution`).join('; ')}))));
  $('export-audit').addEventListener('click',()=>O.download('slacheck-audit.csv',[...O.ticketHeaders,'response_minutes','response_target_minutes','response_status','resolution_minutes','resolution_target_hours','resolution_status','open_age_hours','cutoff_utc'],audit.tickets.map(r=>({...r,response_minutes:r.response.minutes.toFixed(2),response_target_minutes:rules[r.priority].response,response_status:r.response.status,resolution_minutes:r.resolution.minutes.toFixed(2),resolution_target_hours:rules[r.priority].resolution,resolution_status:r.resolution.status,open_age_hours:r.resolution.complete?'':r.ageHours.toFixed(2),cutoff_utc:cutoff}))));
  $('export-actions').addEventListener('click',()=>O.download('slacheck-corrective-actions.csv',['ticket_id','vendor','priority','owner','response_status','resolution_status','action','due_date','status','evidence','notes'],actionRows()));
  function availability(){try{const days=O.number($('period').value,'Period days',{min:0.001,max:3660}),minutes=days*1440,down=O.number($('downtime').value,'Downtime',{max:minutes}),target=O.number($('target').value,'Availability target',{max:100}),actual=(minutes-down)/minutes*100,allowed=minutes*(1-target/100);message('availability',`${actual.toFixed(4)}% availability · ${actual+1e-10>=target?'Target met':'Below target'} · Allowed downtime: ${allowed.toFixed(2)} min · Actual downtime: ${down.toFixed(2)} min · Period: ${days} days.`,actual+1e-10<target);}catch(err){message('availability',err.message,true);}}
  $('availability-form').addEventListener('submit',ev=>{ev.preventDefault();availability();});
  $('print').addEventListener('click',()=>window.print());render();availability();
})();
