/* Run in a browser after core.js. No network or third-party dependencies. */
function runOpsTests() {
  const O = Ops, results = [];
  const test = (name, fn) => { try { fn(); results.push({name,pass:true}); } catch(e) { results.push({name,pass:false,error:e.message}); } };
  const equal = (a,b) => { if(JSON.stringify(a)!==JSON.stringify(b)) throw Error(`Expected ${JSON.stringify(b)}, got ${JSON.stringify(a)}`); };
  const throws = fn => { let threw=false;try{fn();}catch{threw=true;}if(!threw)throw Error('Expected an error'); };
  const spend = extra => O.validateSpend({date:'2026-09-01',vendor:'Acme',invoice:'INV-1',sku:'MON',description:'Monitor',quantity:'2',unit_price:'100',tax:'10',shipping:'5',paid:'100',unit:'each',due_date:'2026-09-02',preferred:'false',strategic:'false',entry_type:'purchase',...extra});
  const ticket = extra => O.validateTicket({ticket_id:'T1',vendor:'Vendor',priority:'P1',opened_at:'2026-09-01T00:00:00Z',responded_at:'2026-09-01T00:15:00Z',resolved_at:'2026-09-01T04:00:00Z',...extra});
  const rules = O.defaultRules, cutoff='2026-09-02T00:00:00Z';
  test('CSV BOM, CRLF, quoted comma and embedded newline',()=>equal(O.parseCSV('\uFEFFa,b\r\n"one,two","a\n""b"""\r\n').rows,[{a:'one,two',b:'a\n"b"'}]));
  test('CSV rejects missing closing quote',()=>throws(()=>O.parseCSV('a,b\n"bad,x')));
  test('CSV rejects extra values',()=>throws(()=>O.parseCSV('a,b\nx,y,z')));
  test('CSV rejects duplicate headers',()=>throws(()=>O.parseCSV('a,A\nx,y')));
  test('CSV rejects text after quote',()=>throws(()=>O.parseCSV('a\n"x"z')));
  test('CSV handles empty trailing field',()=>equal(O.parseCSV('a,b\nx,').rows,[{a:'x',b:''}]));
  test('Spreadsheet formula export neutralization',()=>equal(O.parseCSV(O.csv(['x'],[{x:'=1+1'},{x:' @SUM(A1)'},{x:'\t-2'}])).rows.map(r=>r.x),["'=1+1","' @SUM(A1)","'\t-2"]));
  test('HTML escaping',()=>equal(O.escape('<img onerror="x">'), '&lt;img onerror=&quot;x&quot;&gt;'));
  test('Invalid calendar date rejected',()=>throws(()=>O.date('2026-02-30','Date')));
  test('Invalid time rejected',()=>throws(()=>O.timestamp('2026-09-01T24:00:00Z','Time')));
  test('Timezone is required',()=>throws(()=>O.timestamp('2026-09-01T12:00:00','Time')));
  test('Timezone offsets are honored',()=>equal(O.timestamp('2026-09-01T03:00:00+03:00','Time'),O.timestamp('2026-09-01T00:00:00Z','Time')));
  test('Reject negative purchase values',()=>throws(()=>spend({unit_price:'-2'})));
  test('Reject unknown boolean flags',()=>throws(()=>spend({preferred:'yes'})));
  test('Reject payments on estimates',()=>throws(()=>spend({entry_type:'estimate'})));
  test('Purchase total includes line tax and shipping',()=>equal(O.lineTotal(spend({})),21500));
  test('Money rounds at each line',()=>equal(O.lineTotal(spend({quantity:'3',unit_price:'0.1',tax:'0',shipping:'0'})),30));
  test('Estimates excluded from booked and unpaid totals',()=>{const a=O.analyzeSpend([spend({}),spend({entry_type:'estimate',paid:'0'})],1000,'2026-09-03');equal([a.total,a.estimates,a.unpaid,a.overdue],[21500,21500,11500,11500]);});
  test('Tail threshold excludes exact boundary',()=>equal(O.analyzeSpend([spend({})],215,'2026-09-03').tail,0));
  test('Strategic supplier excluded across all lines',()=>equal(O.analyzeSpend([spend({}),spend({strategic:'true'})],1000,'2026-09-03').tail,0));
  test('Vendor identity matches case and spaces only',()=>{const a=O.analyzeSpend([spend({vendor:' ACME '}),spend({vendor:'acme'}),spend({vendor:'Acme Inc.'})],1000,'2026-09-03');equal(a.suppliers.length,2);});
  test('Duplicate candidates require matching invoice lines',()=>equal(O.analyzeSpend([spend({}),spend({}),spend({invoice:'INV-2'})],1000,'2026-09-03').duplicateGroups[0].length,2));
  test('Missing invoice is never duplicate evidence',()=>equal(O.analyzeSpend([spend({invoice:''}),spend({invoice:''})],1000,'2026-09-03').duplicateGroups.length,0));
  test('Price variance compares same SKU and unit',()=>{const a=O.analyzeSpend([spend({unit_price:'100'}),spend({unit_price:'120'}),spend({unit_price:'5',unit:'pack'})],1000,'2026-09-03');equal([a.variance.length,a.variance[0].opportunity],[1,4000]);});
  test('Payment excess tracked separately from unpaid',()=>{const a=O.analyzeSpend([spend({paid:'250'})],1000,'2026-09-03');equal([a.unpaid,a.overpaid],[0,3500]);});
  test('Due date today not overdue',()=>equal(O.analyzeSpend([spend({})],1000,'2026-09-02').overdue,0));
  test('Exact SLA deadlines met',()=>{const a=O.auditTickets([ticket({})],rules,cutoff);equal([a.compliance,a.responseBreaches,a.resolutionBreaches],[100,0,0]);});
  test('SLA one second late breaches',()=>equal(O.auditTickets([ticket({responded_at:'2026-09-01T00:15:01Z'})],rules,cutoff).responseBreaches,1));
  test('Unresponded within deadline remains pending',()=>{const a=O.auditTickets([ticket({responded_at:'',resolved_at:''})],rules,'2026-09-01T00:10:00Z');equal([a.compliance,a.pending,a.open],[null,2,1]);});
  test('Overdue unresolved milestones count as breaches',()=>{const a=O.auditTickets([ticket({responded_at:'',resolved_at:''})],rules,cutoff);equal([a.compliance,a.responseBreaches,a.resolutionBreaches],[0,1,1]);});
  test('Future milestones treated as incomplete at cutoff',()=>{const a=O.auditTickets([ticket({})],rules,'2026-09-01T00:10:00Z');equal([a.pending,a.open],[2,1]);});
  test('Opening after cutoff rejected',()=>throws(()=>O.auditTickets([ticket({})],rules,'2026-08-01T00:00:00Z')));
  test('Duplicate vendor ticket IDs rejected',()=>throws(()=>O.auditTickets([ticket({}),ticket({})],rules,cutoff)));
  test('Ticket IDs can repeat across vendors',()=>equal(O.auditTickets([ticket({}),ticket({vendor:'Other'})],rules,cutoff).count,2));
  test('Response cannot precede opening',()=>throws(()=>ticket({responded_at:'2026-08-31T23:00:00Z'})));
  test('Resolved ticket requires response evidence',()=>throws(()=>ticket({responded_at:''})));
  test('Response cannot follow resolution',()=>throws(()=>ticket({responded_at:'2026-09-01T05:00:00Z'})));
  test('Repeat issues require matching vendor',()=>{const a=O.auditTickets([ticket({issue_key:'rack'}),ticket({ticket_id:'T2',issue_key:'rack'}),ticket({vendor:'Other',issue_key:'rack'})],rules,cutoff);equal(a.repeats[0].length,2);});
  return results;
}
