/* global Ops */
(function () {
  'use strict';
  const O = Ops, $ = id => document.getElementById(id), e = O.escape, dollars = n => O.money(n / 100);
  let rows = [], editing = -1, threshold = 10000, asOf = new Date().toISOString().slice(0,10), analysis;
  const form = $('entry-form');
  const catalog = [
    { sku:'PLAN-LAP-16', name:'Everyday business laptop', spec:'16 GB RAM · 512 GB SSD · 14–15″ display', category:'IT hardware', price:850, icon:'▱' },
    { sku:'PLAN-LAP-32', name:'Developer laptop', spec:'32 GB RAM · 1 TB SSD · 14–16″ display', category:'IT hardware', price:1450, icon:'⌘' },
    { sku:'PLAN-MON-27', name:'27″ QHD monitor', spec:'2560 × 1440 · adjustable stand · each', category:'IT hardware', price:240, icon:'▣' },
    { sku:'PLAN-DOCK-USB', name:'USB-C docking station', spec:'Dual display · Ethernet · power delivery', category:'IT hardware', price:160, icon:'⊞' },
    { sku:'PLAN-SW-24', name:'24-port managed switch', spec:'1 GbE · rack mount · non-PoE', category:'Networking', price:320, icon:'☷' },
    { sku:'PLAN-SSD-2T', name:'2 TB NVMe SSD', spec:'M.2 2280 · PCIe 4.0 · each', category:'Storage', price:140, icon:'▤' }
  ];
  $('catalog').innerHTML = catalog.map((p,i) => `<article class="sku"><span class="sku-icon" aria-hidden="true">${p.icon}</span><h3>${p.name}</h3><p>${p.spec}<br><code>${p.sku}</code></p><div class="price">${O.money(p.price)} <small>/ each</small></div><button class="small" data-sku="${i}">Use sample estimate +</button></article>`).join('');
  const message = (id, text, error = false) => { $(id).textContent = text; $(id).classList.toggle('error', error); };
  function resetForm() { form.reset(); form.elements.date.value = new Date().toISOString().slice(0,10); editing = -1; $('entry-title').textContent = 'Add a purchase or estimate'; $('save-entry').textContent = 'Add to ledger +'; $('cancel-edit').hidden = true; preview(); }
  function preview() { const f = form.elements; const n = Number(f.quantity.value)*Number(f.unit_price.value)+Number(f.tax.value)+Number(f.shipping.value); $('line-preview').textContent = `Line total: ${O.money(n)} · before subtracting payments`; }
  form.addEventListener('input',preview);
  $('catalog').addEventListener('click',ev => { const b = ev.target.closest('[data-sku]'); if (!b) return; resetForm(); const p = catalog[+b.dataset.sku]; for (const [k,v] of Object.entries({ sku:p.sku, description:p.name+' — '+p.spec, category:p.category, unit_price:p.price, entry_type:'estimate' })) form.elements[k].value = v; preview(); $('entry').scrollIntoView({ behavior:'smooth', block:'start' }); form.elements.vendor.focus({ preventScroll:true }); message('entry-status','Sample estimate loaded. Enter a supplier or “To source”, adjust the quote, and add it to your ledger.'); });
  form.addEventListener('submit',ev => { ev.preventDefault(); try { const r = O.validateSpend(Object.fromEntries(new FormData(form))); if (editing < 0 && rows.length >= 10000) throw new Error('The workspace supports at most 10,000 rows.'); if (editing < 0) rows.push(r); else rows[editing] = r; resetForm(); render(); message('entry-status','Saved to this session. Download the ledger CSV to keep your work.'); } catch (err) { message('entry-status',err.message,true); } });
  $('cancel-edit').addEventListener('click',() => { resetForm(); message('entry-status','Edit canceled.'); });
  $('ledger').addEventListener('click',ev => { const b = ev.target.closest('button'); if (!b) return; const i = +b.dataset.index; if (b.dataset.action === 'remove') { rows.splice(i,1); resetForm(); render(); message('status','Row removed from the workspace.'); } else { editing = i; for (const h of O.spendHeaders) form.elements[h].value = String(rows[i][h]); $('entry-title').textContent = 'Edit ledger row'; $('save-entry').textContent = 'Save changes'; $('cancel-edit').hidden = false; preview(); $('entry').scrollIntoView({ behavior:'smooth' }); form.elements.vendor.focus({ preventScroll:true }); } });
  $('template').addEventListener('click',() => O.download('spendcheck-template.csv',O.spendHeaders,[]));
  $('import').addEventListener('change',async ev => { try { const imported = await O.readFile(ev.target.files[0],['date','vendor','description','quantity','unit_price'],O.validateSpend); if (!imported) return; rows = imported; resetForm(); render(); message('status',`Imported ${rows.length} rows. Previous workspace replaced. All calculations are local.`); } catch (err) { message('status',err.message + ' Your current ledger is unchanged.',true); } finally { ev.target.value = ''; } });
  $('sample').addEventListener('click',() => { const base = { date:asOf, vendor:'Northstar IT', invoice:'INV-1001', po:'PO-001', sku:'PLAN-MON-27', description:'27 inch QHD monitor', category:'IT hardware', cost_center:'IT-OPS', gl_account:'', quantity:'4', unit:'each', unit_price:'240', tax:'0', shipping:'0', paid:'960', due_date:asOf, preferred:'true', strategic:'false', entry_type:'purchase' }; rows = [base,{ ...base,vendor:'Office Direct',invoice:'INV-210',quantity:'3',unit_price:'285',paid:'0',preferred:'false' },{ ...base,vendor:'Office Direct',invoice:'INV-210',quantity:'3',unit_price:'285',paid:'0',preferred:'false' },{ ...base,vendor:'Northstar IT',invoice:'INV-1002',sku:'PLAN-LAP-16',description:'Business laptop, 16 GB',quantity:'12',unit_price:'850',paid:'5000',strategic:'true' },{ ...base,vendor:'Desk Supply Co',invoice:'INV-78',sku:'CAB-USB-C',description:'USB-C cable, 2 m',category:'',quantity:'20',unit_price:'12',paid:'240',preferred:'false' },{ ...base,vendor:'To source',invoice:'',sku:'PLAN-SW-24',description:'24-port managed switch',category:'Networking',quantity:'2',unit_price:'320',paid:'0',entry_type:'estimate',preferred:'false' }].map(O.validateSpend); resetForm(); render(); message('status','Example loaded — fictional purchases and sample prices. It replaces the previous workspace.'); });
  $('clear').addEventListener('click',() => { rows = []; resetForm(); render(); message('status','Workspace cleared.'); });
  $('settings').addEventListener('submit',ev => { ev.preventDefault(); try { threshold = O.number($('threshold').value,'Threshold'); asOf = O.date($('as-of').value,'As-of date'); render(); message('status','Tail threshold and balance date updated.'); } catch(err) { message('status',err.message,true); } });
  $('merge-form').addEventListener('submit',ev => { ev.preventDefault(); const alias = $('alias').value, canonical = $('canonical').value.trim(); if (!alias || !canonical) return; let count = 0; rows = rows.map(r => O.key(r.vendor) === alias ? (count++, { ...r,vendor:canonical }) : r); resetForm(); render(); message('merge-status',`${count} rows now use ${canonical}.`); });
  const empty = (cols, text) => `<tr><td colspan="${cols}" class="empty">${text}</td></tr>`;
  function reviewRows() {
    const a = analysis, result = [];
    for (const g of a.duplicateGroups) result.push({ type:'Possible duplicate', vendor:g[0].vendor, reference:g[0].invoice, amount_to_review:((g.length-1)*O.lineTotal(g[0])/100).toFixed(2), note:`${g.length} matching invoice lines. Confirm against source invoice; no rows removed.` });
    if (a.outside) result.push({ type:'Outside preferred suppliers',vendor:'',reference:'',amount_to_review:(a.outside/100).toFixed(2),note:'Rows marked preferred=false or left unspecified.' });
    if (a.uncategorized) result.push({ type:'Missing category',vendor:'',reference:'',amount_to_review:(a.uncategorized/100).toFixed(2),note:'Assign categories before reporting.' });
    if (a.overpaid) result.push({ type:'Payment exceeds line total',vendor:'',reference:'',amount_to_review:(a.overpaid/100).toFixed(2),note:'Review payment allocation or possible overpayment.' });
    return result;
  }
  function render() {
    analysis = O.analyzeSpend(rows,threshold,asOf); const a = analysis;
    const metrics = [['Booked spend',dollars(a.total),`${a.purchases.length} purchase lines · ${a.suppliers.length} suppliers`],['Tail spend',dollars(a.tail),`${a.suppliers.filter(s => s.tail).length} suppliers below ${O.money(threshold)}`],['Outstanding balance',dollars(a.unpaid),`${dollars(a.overdue)} overdue as of ${asOf}`],['Budget estimates',dollars(a.estimates),'Separate from booked spend and balances']];
    $('metrics').innerHTML = metrics.map(([label,value,note],i) => `<div class="metric ${i===0?'featured':''}"><div class="metric-label">${e(label)}</div><div class="metric-value">${e(value)}</div><div class="metric-note">${e(note)}</div></div>`).join('');
    const dates = a.purchases.map(r => r.date).sort(); $('scope').textContent = dates.length ? `Imported purchase period: ${dates[0]} to ${dates.at(-1)} · All amounts in USD.` : 'No booked purchases yet. Import a CSV or add a row to begin.';
    $('ledger-count').textContent = `${rows.length} rows · ${rows.filter(r => r.entry_type === 'estimate').length} estimates · ${rows.length > 200 ? 'Showing first 200; exports include all rows' : 'Editable in this session'}`;
    $('ledger').innerHTML = rows.slice(0,200).map((r,i) => `<tr><td>${e(r.date)}<small>${e(r.invoice || 'No invoice')}</small></td><td><strong>${e(r.vendor)}</strong><small>${e(r.description)}</small></td><td>${e(r.sku || '—')}<small>${e(r.category || 'Uncategorized')}</small></td><td>${r.quantity}<small>${e(r.unit)}</small></td><td class="num">${dollars(O.lineTotal(r))}</td><td class="num">${r.entry_type==='estimate'?'—':dollars(Math.max(0,O.lineTotal(r)-O.cents(r.paid)))}</td><td><span class="badge ${r.entry_type==='estimate'?'warn':''}">${e(r.entry_type)}</span></td><td class="no-print"><div class="actions"><button class="small" data-action="edit" data-index="${i}" aria-label="Edit row ${i+1}">Edit</button><button class="small danger" data-action="remove" data-index="${i}" aria-label="Remove row ${i+1}">×</button></div></td></tr>`).join('') || empty(8,'<strong>Your ledger starts here.</strong>Add a purchase, use a hardware estimate, or load the example above.');
    $('balances').textContent = `Line total = rounded(quantity × unit price) + tax + shipping. Purchase payments: ${dollars(a.purchases.reduce((n,r)=>n+O.cents(r.paid),0))}. Payment excess to review: ${dollars(a.overpaid)}. Balances are clamped at zero per line.`;
    $('suppliers').innerHTML = a.suppliers.slice(0,100).map(s => `<tr><td>${e(s.vendor)}<small>${s.rows} lines</small></td><td class="num">${dollars(s.total)}</td><td class="num">${a.total?(s.total/a.total*100).toFixed(1):'0.0'}%<div class="bar"><span style="width:${a.total?s.total/a.total*100:0}%"></span></div></td><td><span class="badge ${s.tail?'warn':''}">${s.strategic?'Strategic':s.tail?'Tail':'Core'}</span></td></tr>`).join('') || empty(4,'Supplier totals appear after you add purchases.');
    const reviews = reviewRows(); $('review').innerHTML = reviews.slice(0,50).map(r => `<div class="panel-body" style="border-bottom:1px solid var(--line)"><div class="section-label" style="margin-bottom:4px"><h3>${e(r.type)}</h3><span class="badge warn">${O.money(+r.amount_to_review)}</span></div><div class="helper">${e([r.vendor,r.reference].filter(Boolean).join(' · '))} ${e(r.note)}</div></div>`).join('') || '<div class="empty">'+(rows.length?'No review flags under the current checks.':'Add purchases to check duplicates, categories, and supplier flags.')+'</div>';
    $('display-limits').hidden = rows.length<=200 && a.suppliers.length<=100 && a.variance.length<=100 && reviews.length<=50;
    $('variance').innerHTML = a.variance.slice(0,100).map(r => `<tr><td>${e(r.sku)}<small>${r.vendors} suppliers</small></td><td>${e(r.unit)}</td><td class="num">${O.money(r.low)}</td><td class="num">${O.money(r.high)}</td><td class="num">${dollars(r.opportunity)}</td></tr>`).join('') || empty(5,'No unit price differences found for matching SKU + unit pairs.');
    $('alias').innerHTML = [...new Map(rows.map(r => [O.key(r.vendor),r.vendor])).entries()].map(([k,v]) => `<option value="${e(k)}">${e(v)}</option>`).join('');
    for (const id of ['export-ledger','print','export-review','rfq','export-suppliers']) $(id).disabled = !rows.length;
  }
  $('export-ledger').addEventListener('click',() => O.download('spendcheck-ledger.csv',[...O.spendHeaders,'line_total','balance','payment_excess'],rows.map(r => ({ ...r,line_total:(O.lineTotal(r)/100).toFixed(2),balance:r.entry_type==='estimate'?'':(Math.max(0,O.lineTotal(r)-O.cents(r.paid))/100).toFixed(2),payment_excess:r.entry_type==='estimate'?'':(Math.max(0,O.cents(r.paid)-O.lineTotal(r))/100).toFixed(2) }))));
  $('export-review').addEventListener('click',() => O.download('spendcheck-review.csv',['type','vendor','reference','amount_to_review','note'],reviewRows()));
  $('export-suppliers').addEventListener('click',() => O.download('spendcheck-suppliers.csv',['vendor','spend_usd','purchase_lines','share_percent','segment','dataset_tail_threshold_usd'],analysis.suppliers.map(s => ({ vendor:s.vendor,spend_usd:(s.total/100).toFixed(2),purchase_lines:s.rows,share_percent:analysis.total?(s.total/analysis.total*100).toFixed(2):'0',segment:s.strategic?'strategic':s.tail?'tail':'core',dataset_tail_threshold_usd:threshold }))));
  $('rfq').addEventListener('click',() => { const groups = new Map(); rows.filter(r => r.sku).forEach(r => { const k = JSON.stringify([O.key(r.sku),O.key(r.unit),r.entry_type]); if (!groups.has(k)) groups.set(k,{ sku:r.sku,description:r.description,category:r.category,unit:r.unit,source_type:r.entry_type,reference_quantity:0,reference_unit_price_usd:r.unit_price,requested_quantity:'',supplier:'',quoted_unit_price_usd:'',lead_time_days:'',quote_valid_until:'',warranty:'',notes:'Reference quantities are historical purchases or estimates; enter the actual quantity to source.' }); const g=groups.get(k); g.reference_quantity+=r.quantity; g.reference_unit_price_usd=Math.min(g.reference_unit_price_usd,r.unit_price); }); const result=[...groups.values()]; O.download('spendcheck-rfq.csv',['sku','description','category','unit','source_type','reference_quantity','reference_unit_price_usd','requested_quantity','supplier','quoted_unit_price_usd','lead_time_days','quote_valid_until','warranty','notes'],result); });
  $('print').addEventListener('click',() => window.print());
  $('as-of').value = asOf; resetForm(); render();
})();
